[package]
name = "log_strip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
process_mining = "0.3.13"
chrono = "0.4.38"
indicatif = "0.17.8"