[package]
name = "event_hours_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "event_hours_analyzer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
process_mining = "0.3.13"

