
on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu,x86_64-unknown-linux-musl]
        package: [log_strip,ocel_graph/backend]
        include:
        - package: log_strip
          package_name: log_strip
        - package: ocel_graph/backend
          package_name: ocel_graph_backend
        - target: x86_64-pc-windows-gnu
          target_name: windows
        - target: x86_64-unknown-linux-musl
          target_name: linux
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: ${{ matrix.package }}
          ARCHIVE_NAME: ${{matrix.package_name}}-${{matrix.target_name}}
